spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare_db
    username: postgres
    password: rcdev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
